steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proudofmom-web:$_PR_NUMBER', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proudofmom-web:$_PR_NUMBER']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '$_PREFIX-proudofmom-web', '--image', 'gcr.io/$PROJECT_ID/proudofmom-web:$_PR_NUMBER', '--port', '3000', '--set-env-vars', 'NEXT_PUBLIC_API_URL=${_API_PREFIX}.proudofmom.com/graphql', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
  # Create mapping domain
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run','domain-mappings','create','--service', '$_PREFIX-proudofmom-web', '--domain', 'stage${_PR_NUMBER}.proudofmom.com', '--force-override', '--region', 'us-central1', '--platform', 'managed']
images:
- gcr.io/$PROJECT_ID/proudofmom-web:$_PR_NUMBER