steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'NEXT_PUBLIC_API_URL=https://$_API_PREFIX.proudofmom.com/graphql', 'gcr.io/$PROJECT_ID/proudofmom-web', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proudofmom-web:$_PR_NUMBER']
  # Delete mapping domain
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run','domain-mappings', 'delete', '--domain', 'stage${_PR_NUMBER}.proudofmom.com', '--region', 'us-central1', '--platform', 'managed']
  # Create mapping domain
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run','domain-mappings', 'create','--service', '$_PREFIX-proudofmom-web', '--force-override', '--domain', 'stage${_PR_NUMBER}.proudofmom.com', '--region', 'us-central1', '--platform', 'managed']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '$_PREFIX-proudofmom-web', '--image', 'gcr.io/$PROJECT_ID/proudofmom-web', '--port', '3000', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/$PROJECT_ID/proudofmom-web