steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proudofmom-web:$_PR_NUMBER', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/proudofmom-web:$_PR_NUMBER']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'staging-proudofmom-web', '--image', 'gcr.io/$PROJECT_ID/proudofmom-web:$_PR_NUMBER', '--port', '3000', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
  # Create DNS mapping
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['./dns_mapping.sh']
    env:
    - 'XNSONEKEY=$_XNSONEKEY'
    - 'PR_NUMBER=$_PR_NUMBER'
  # Create mapping domain
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run','domain-mappings','create','--service', 'staging-proudofmom-web', '--domain', 'stage${_PR_NUMBER}.proudofmom.com', '--region', 'us-central1', '--platform', 'managed']
images:
- gcr.io/$PROJECT_ID/proudofmom-web:$_PR_NUMBER